name: Deploy Library to Production

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          npm ci

      - name: Build application
        run: |
          npm run build

      - name: Add production server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 42.96.40.246 >> ~/.ssh/known_hosts

      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 42.96.40.246
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PRODUCTION_PORT || 22 }}
          script: |
            cd /srv/app/library

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git .
            else
              git fetch origin
              git reset --hard origin/${{ github.ref_name }}
            fi

            # Install and build
            npm ci --production
            npm run build

            # Restart app
            if command -v pm2 &> /dev/null; then
              pm2 reload library || pm2 start npm --name "library" -- start
            fi

            echo "✅ Deployed successfully"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
